// This file was autogenerated by ../closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../kyoro/hetima/signal/caller.js', ['hetima.signal.Caller'], ['hetima.util.Bdecode', 'hetima.util.Bencode', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/signal/hetimapeer.js', ['hetima.signal.HetimaPeer'], ['goog.ui.ComboBox', 'goog.ui.ComboBoxItem', 'goog.ui.MenuSeparator', 'hetima.signal.Caller', 'hetima.signal.Messenger', 'hetima.signal.SignalClient', 'hetima.signal.UserInfo', 'hetima.util.Bencode', 'hetima.util.Encoder', 'hetima.util.UUID']);
goog.addDependency('../../kyoro/hetima/signal/messenger.js', ['hetima.signal.Messenger'], ['goog.ui.ComboBox', 'goog.ui.ComboBoxItem', 'goog.ui.MenuSeparator', 'hetima.signal.Caller', 'hetima.signal.SignalClient', 'hetima.signal.UserInfo', 'hetima.util.Bdecode', 'hetima.util.Bencode', 'hetima.util.BencodeHelper', 'hetima.util.Encoder', 'hetima.util.UUID']);
goog.addDependency('../../kyoro/hetima/signal/signalclient.js', ['hetima.signal.SignalClient'], ['hetima.util.Bdecode', 'hetima.util.Bencode', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/signal/signalclient_test.js', ['hetima.signal.SignalClientTest'], []);
goog.addDependency('../../kyoro/hetima/signal/signalserver.js', ['hetima.signal.SignalServer'], ['hetima.signal.UserInfo', 'hetima.util.Bdecode', 'hetima.util.Bencode', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/signal/userinfo.js', ['hetima.signal.UserInfo'], []);
goog.addDependency('../../kyoro/hetima/signal/userinfo_test.js', ['hetima.signal.UserInfoTest'], ['goog.testing.jsunit', 'hetima.signal.UserInfo']);
goog.addDependency('../../kyoro/hetima/util/arraybuilder.js', ['hetima.util.ArrayBuilder'], []);
goog.addDependency('../../kyoro/hetima/util/arraybuilder_test.js', ['hetima.util.ArrayBuilderTest'], ['goog.testing.jsunit', 'hetima.util.ArrayBuilder']);
goog.addDependency('../../kyoro/hetima/util/bdecode.js', ['hetima.util.Bdecode'], ['hetima.util.ArrayBuilder', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/util/bencode.js', ['hetima.util.Bencode'], ['hetima.util.ArrayBuilder', 'hetima.util.Bdecode']);
goog.addDependency('../../kyoro/hetima/util/bencode_test.js', ['hetima.util.BencodeTest'], ['goog.testing.jsunit', 'hetima.util.ArrayBuilder', 'hetima.util.Bdecode', 'hetima.util.Bencode', 'hetima.util.BencodeHelper', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/util/bencodehelper.js', ['hetima.util.BencodeHelper'], ['hetima.util.ArrayBuilder', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/util/encoder.js', ['hetima.util.Encoder'], ['hetima.util.ArrayBuilder']);
goog.addDependency('../../kyoro/hetima/util/encoder_test.js', ['hetima.util.EncoderTest'], ['goog.testing.jsunit', 'hetima.util.Encoder']);
goog.addDependency('../../kyoro/hetima/util/uuid.js', ['hetima.util.UUID'], []);
goog.addDependency('../../kyoro/hetima/util/uuid_test.js', ['hetima.util.UUIDTest'], ['goog.testing.jsunit', 'hetima.util.UUID']);
