// This file was autogenerated by ../../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../sample/005/model.js', ['AppModel'], ['AppView', 'goog.dom', 'goog.ui.ComboBox', 'goog.ui.ComboBoxItem', 'goog.ui.MenuSeparator', 'hetima.signal.Caller', 'hetima.signal.SignalClient', 'hetima.signal.UserInfo', 'hetima.util.BencodeHelper', 'hetima.util.UUID']);
goog.addDependency('../../../sample/005/view.js', ['AppView'], ['goog.dom', 'goog.ui.ComboBox', 'goog.ui.ComboBoxItem', 'goog.ui.MenuSeparator', 'hetima.signal.Caller', 'hetima.signal.SignalClient', 'hetima.signal.UserInfo', 'hetima.util.BencodeHelper', 'hetima.util.UUID']);
